INSERT INTO semester (semester_id, batch_id, semester_name)
VALUES (2, 1, '2nd');
INSERT INTO sem (semester_id, batch_name, semester_name) 
VALUES 
(1, '2021-2025', 'S1'),
(2, '2021-2025', 'S2'),
(3, '2021-2025', 'S3'),
(4, '2021-2025', 'S4'),
(5, '2021-2025', 'S5'),
(6, '2021-2025', 'S6'),
(7, '2021-2025', 'S7'),
(8, '2021-2025', 'S8');
CREATE TABLE s1 (
    UID VARCHAR(50),
    Batch VARCHAR(50),
    Semester_id INT,
    Semester_name VARCHAR(50),
    Name VARCHAR(100),
    LAC_Marks INT,
    LAC_grade VARCHAR(5),
    Engg_Chem_Marks INT,
    Engg_Chem_grade VARCHAR(5),
    Engg_Graphics_Marks INT,
    Engg_Graphics_Grade VARCHAR(5),
    Basics_CE_ME_Marks INT,
    Basics_CE_ME_Grade VARCHAR(5),
    LS_Marks INT,
    LS_Grade VARCHAR(5),
    Chem_Lab_Marks INT,
    Chem_Lab_Grade VARCHAR(5),
    Workshop_Marks INT,
    Workshop_Grade VARCHAR(5),
    sgpa FLOAT,
    cgpa FLOAT,
    FOREIGN KEY (semester_id) REFERENCES sem(semester_id)
);

CREATE TABLE s2 (
    UID VARCHAR(50),
    Batch VARCHAR(50),
    Semester_id INT,
    Semester_name VARCHAR(50),
    Name VARCHAR(100),
    Vector_calculus_Marks INT,
    Vector_calculus_grade VARCHAR(5),
    Engg_Physics_Marks INT,
    Engg_Physics_grade VARCHAR(5),
    Engg_Mechanics_Marks INT,
    Engg_Mechanics_grade VARCHAR(5),
    Professional_Communication_Marks INT,
    Professional_Communication_Grade VARCHAR(5),
    Basics_of_Electronic_and_Electricals_Marks INT,
    Basics_of_Electronic_and_Electricals_grade VARCHAR(5),
    Programming_in_C_Marks INT,
    Programming_in_C_grade VARCHAR(5),
    engg_physics_lab_Marks INT,
    engg_physics_lab_grade VARCHAR(5),
    Electrical_electronic_lab_mark INT,
    Electrical_electronic_lab_grade VARCHAR(5),
    sgpa FLOAT,
    cgpa FLOAT,
    FOREIGN KEY (semester_id) REFERENCES sem(semester_id)
);
CREATE TABLE s3 (
    UID VARCHAR(50),
    Batch VARCHAR(50),
    Semester_id INT,
    Semester_name VARCHAR(50),
    Name VARCHAR(100),
    DMS_Marks INT,
    DMS_grade VARCHAR(5),
    DS_Marks INT,
    DS_grade VARCHAR(5),
    DSD_Marks INT,
    DSD_grade VARCHAR(5),
    Python_Marks INT,
    Python_grade VARCHAR(5),
    Design_and_engineering_Marks INT,
    Design_and_engineering_grade VARCHAR(5),
    Sustainable_engineering_Marks INT,
    Sustainable_engineering_grade VARCHAR(5),
    DS_lab_Marks INT,
    DS_lab_grade VARCHAR(5),
    Python_lab_mark INT,
    Python_lab_grade VARCHAR(5),
    sgpa FLOAT,
    cgpa FLOAT,
    FOREIGN KEY (semester_id) REFERENCES sem(semester_id)
);
CREATE TABLE s4 (
    UID VARCHAR(50),
    Batch VARCHAR(50),
    Semester_id INT,
    Semester_name VARCHAR(50),
    Name VARCHAR(100),
    Principles_Of_Object_Oriented_Techniques_Marks INT,
    Principles_Of_Object_Oriented_Techniques_Grade VARCHAR(5),
    Graph_Theory_Marks INT NULL,
    Graph_Theory_grade VARCHAR(5),
    Computer_Organization_Marks INT NULL,
    Computer_Organization_grade VARCHAR(5),
    Database_Management_Systems_Marks INT NULL,
    Database_Management_Systems_grade VARCHAR(5),
    Professional_Ethics_Marks INT NULL,
    Professional_Ethics_grade VARCHAR(5),
    Constitution_Of_India_Marks INT NULL,
    Constitution_Of_India_grade VARCHAR(5),
    Object_Oriented_Techniques_Lab_Marks INT NULL,
    Object_Oriented_Techniques_Lab_grade VARCHAR(5),
    Database_Management_Systems_Lab_Marks INT NULL,
    Database_Management_Systems_Lab_grade VARCHAR(5),
    sgpa FLOAT NULL,
    cgpa FLOAT NULL,
    FOREIGN KEY (Semester_id) REFERENCES sem(Semester_id)
);
CREATE TABLE s5 (
    UID VARCHAR(10) PRIMARY KEY,
    Batch VARCHAR(10),
    Semester_id INT,
    Semester_Name VARCHAR(5),
    Name VARCHAR(100),
    Web_Application_Development_Marks INT,
    Web_Application_Development_grade CHAR(1),
    Operating_System_Concepts_Marks INT,
    Operation_System_Concepts_grade CHAR(1),
    Data_Communication_and_Networking_Marks INT,
    Data_Communication_and_Networking_grade CHAR(1),
    Formal_Languages_and_Automata_Theory_Marks INT,
    Formal_Languages_and_Automata_Theory_grade CHAR(1),
    Management_For_Software_Engineers_Marks INT,
    Management_For_Software_Engineers_grade CHAR(1),
    Disaster_Management_Marks INT,
    Disaster_Management_grade CHAR(1),
    Operating_System_and_Network_Programming_Lab_Marks INT,
    Operating_System_and_Network_Programming_Lab_grade CHAR(1),
    Web_Application_Development_Lab_Marks INT,
    Web_Application_Development_Lab_grade CHAR(1),
    SGPA DECIMAL(3,1),
    CGPA DECIMAL(3,1)
);
CREATE TABLE s6 (
    UID VARCHAR(10) PRIMARY KEY,
    Batch VARCHAR(10),
    Semester_id INT,
    Semester_Name VARCHAR(5),
    Name VARCHAR(100),
    Internetworking_with_TCP_IP_Marks INT,
    Internetworking_with_TCP_IP_Grade CHAR(1),
    Algorithm_Analysis_and_Design_Marks INT,
    Algorithm_Analysis_and_Design_Grade CHAR(1),
    Data_Science_Marks INT,
    Data_Science_Grade CHAR(1),
    Soft_Computing_Marks INT,
    Soft_Computing_Grade CHAR(1),
    Digital_Image_Processing_Marks INT,
    Digital_Image_Processing_Grade CHAR(1),
    Industrial_Economics_and_Foreign_Trade_Marks INT,
    Industrial_Economics_and_Foreign_Trade_Grade CHAR(1),
    Computer_Networks_Lab_Marks INT,
    Computer_Networks_Lab_Grade CHAR(1),
    Miniproject_Marks INT,
    Miniproject_Grade CHAR(1),
    SGPA DECIMAL(3,1),
    CGPA DECIMAL(3,1)
);